export const data = [
  {id: 1, name: "SPACE", text: "Aliquam ornare mauris ex, sed tincidunt neque facilisis id. Maecenas vitae ante nec massa varius volutpat. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent congue orci et nunc ultricies dapibus. Aliquam condimentum porttitor nulla. Phasellus suscipit risus sit amet mi interdum faucibus. Quisque egestas lorem ante, id eleifend velit mattis nec. ", link: ""},
  {id: 2, name: "SPACE 2", text: "Aliquam ornare mauris ex, sed tincidunt neque facilisis id. Maecenas vitae ante nec massa varius volutpat. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent congue orci et nunc ultricies dapibus. Aliquam condimentum porttitor nulla. Phasellus suscipit risus sit amet mi interdum faucibus. Quisque egestas lorem ante, id eleifend velit mattis nec. ", link: ""},
  {id: 3, name: "SPACE 3", text: "Aliquam ornare mauris ex, sed tincidunt neque facilisis id. Maecenas vitae ante nec massa varius volutpat. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent congue orci et nunc ultricies dapibus. Aliquam condimentum porttitor nulla. Phasellus suscipit risus sit amet mi interdum faucibus. Quisque egestas lorem ante, id eleifend velit mattis nec. ", link: ""},
  {id: 4, name: "SPACE 4", text: "Aliquam ornare mauris ex, sed tincidunt neque facilisis id. Maecenas vitae ante nec massa varius volutpat. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent congue orci et nunc ultricies dapibus. Aliquam condimentum porttitor nulla. Phasellus suscipit risus sit amet mi interdum faucibus. Quisque egestas lorem ante, id eleifend velit mattis nec. ", link: ""},
  {id: 5, name: "SPACE 5", text: "Aliquam ornare mauris ex, sed tincidunt neque facilisis id. Maecenas vitae ante nec massa varius volutpat. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent congue orci et nunc ultricies dapibus. Aliquam condimentum porttitor nulla. Phasellus suscipit risus sit amet mi interdum faucibus. Quisque egestas lorem ante, id eleifend velit mattis nec. ", link: ""},
  {id: 6, name: "SPACE 6", text: "Aliquam ornare mauris ex, sed tincidunt neque facilisis id. Maecenas vitae ante nec massa varius volutpat. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent congue orci et nunc ultricies dapibus. Aliquam condimentum porttitor nulla. Phasellus suscipit risus sit amet mi interdum faucibus. Quisque egestas lorem ante, id eleifend velit mattis nec. ", link: ""},
  {id: 7, name: "SPACE 7", text: "Aliquam ornare mauris ex, sed tincidunt neque facilisis id. Maecenas vitae ante nec massa varius volutpat. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent congue orci et nunc ultricies dapibus. Aliquam condimentum porttitor nulla. Phasellus suscipit risus sit amet mi interdum faucibus. Quisque egestas lorem ante, id eleifend velit mattis nec. ", link: ""},
  {id: 8, name: "SPACE 8", text: "Aliquam ornare mauris ex, sed tincidunt neque facilisis id. Maecenas vitae ante nec massa varius volutpat. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent congue orci et nunc ultricies dapibus. Aliquam condimentum porttitor nulla. Phasellus suscipit risus sit amet mi interdum faucibus. Quisque egestas lorem ante, id eleifend velit mattis nec. ", link: ""},
  {id: 9, name: "SPACE 9", text: "Aliquam ornare mauris ex, sed tincidunt neque facilisis id. Maecenas vitae ante nec massa varius volutpat. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent congue orci et nunc ultricies dapibus. Aliquam condimentum porttitor nulla. Phasellus suscipit risus sit amet mi interdum faucibus. Quisque egestas lorem ante, id eleifend velit mattis nec. ", link: ""},
  {id: 10, name: "SPACE 10", text: "Aliquam ornare mauris ex, sed tincidunt neque facilisis id. Maecenas vitae ante nec massa varius volutpat. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent congue orci et nunc ultricies dapibus. Aliquam condimentum porttitor nulla. Phasellus suscipit risus sit amet mi interdum faucibus. Quisque egestas lorem ante, id eleifend velit mattis nec. ", link: ""},
  {id: 11, name: "SPACE 11", text: "Aliquam ornare mauris ex, sed tincidunt neque facilisis id. Maecenas vitae ante nec massa varius volutpat. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent congue orci et nunc ultricies dapibus. Aliquam condimentum porttitor nulla. Phasellus suscipit risus sit amet mi interdum faucibus. Quisque egestas lorem ante, id eleifend velit mattis nec. ", link: ""},
  {id: 12, name: "SPACE 12", text: "Aliquam ornare mauris ex, sed tincidunt neque facilisis id. Maecenas vitae ante nec massa varius volutpat. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent congue orci et nunc ultricies dapibus. Aliquam condimentum porttitor nulla. Phasellus suscipit risus sit amet mi interdum faucibus. Quisque egestas lorem ante, id eleifend velit mattis nec. ", link: ""},


]