import type { NextPage } from "next";
import Head from "next/head";
import AboutSection from "./components/content/aboutSection/AboutSection";
import { Content } from "./components/content/messageSection/Content";
import WelcomeSection from "./components/content/welcomeSection/WelcomeSection";
import { Menu } from "./components/menu/Menu";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>IDS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Menu />
        <WelcomeSection />
        <AboutSection />
        <Content />
      </main>
    </div>
  );
};

export default Home;
