import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Menu from './components/menu/Menu'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>IDS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
       <Menu/>
      </main>

      <footer>
       
      </footer>
    </div>
  )
}

export default Home
