import Stage1Icon from "../../../../../../public/svg/stage-1-icon.svg";
import ContentImg from "../../../../../../public/images/contentImage1.png"

export const data = [
  {id: 1, img: Stage1Icon, title: "Stage 1: The Vision", subtitle: "An institution that learns before it teaches", textName: "Summary of stage’s key events ", text: "Strengthening knowledge management becomes an imperative as countries demand IDS offer not just lending, but also bespoke knowledge solutions." , link: "", contentImg: ContentImg.src},
  {id: 2, img: Stage1Icon, title: "Stage 2: The Vision", subtitle: "An institution that learns before it teaches", textName: "Summary of stage’s key events ", text: "Strengthening knowledge management becomes an imperative as countries demand IDS offer not just lending, but also bespoke knowledge solutions." , link: "", contentImg: ContentImg.src},
  {id: 3, img: Stage1Icon, title: "Stage 3: The Vision", subtitle: "An institution that learns before it teaches", textName: "Summary of stage’s key events ", text: "Strengthening knowledge management becomes an imperative as countries demand IDS offer not just lending, but also bespoke knowledge solutions." , link: "", contentImg: ContentImg.src},
  {id: 4, img: Stage1Icon, title: "Stage 4: The Vision", subtitle: "An institution that learns before it teaches", textName: "Summary of stage’s key events ", text: "Strengthening knowledge management becomes an imperative as countries demand IDS offer not just lending, but also bespoke knowledge solutions." , link: "", contentImg: ContentImg.src},
  {id: 5, img: Stage1Icon, title: "Stage 5: The Vision", subtitle: "An institution that learns before it teaches", textName: "Summary of stage’s key events ", text: "Strengthening knowledge management becomes an imperative as countries demand IDS offer not just lending, but also bespoke knowledge solutions." , link: "", contentImg: ContentImg.src},
]